{"DBCallId":"f0144208-3e16-4b08-8a5f-6313c14ec830","TimeStamp":"2024-12-16T14:45:42.0677474-03:00","Query":" SELECT DATA_MOV_ABERTO FROM SEGUROS.SISTEMAS WHERE IDE_SISTEMA = ' ' WITH UR","sqlCode":0,"rowsCount":0,"Time":"0 ms","Error":""}
{"DBCallId":"64c10779-4650-45f9-b2ef-635a9df4acd2","TimeStamp":"2024-12-16T14:45:43.4860488-03:00","Query":"SELECT A.NUM_PROPOSTA_SIVPF , A.NUM_IDENTIFICACAO , A.COD_EMPRESA_SIVPF , A.COD_PESSOA , A.NUM_SICOB , A.DATA_PROPOSTA , A.COD_PRODUTO_SIVPF , A.AGECOBR , A.DIA_DEBITO , A.OPCAOPAG , A.AGECTADEB , A.OPRCTADEB , A.NUMCTADEB , A.DIGCTADEB , A.PERC_DESCONTO , A.NRMATRVEN , A.AGECTAVEN , A.OPRCTAVEN , A.NUMCTAVEN , A.DIGCTAVEN , A.CGC_CONVENENTE , A.NOME_CONVENENTE , A.NRMATRCON , A.DTQITBCO , A.VAL_PAGO , A.AGEPGTO , A.VAL_TARIFA , A.VAL_IOF , A.DATA_CREDITO , A.VAL_COMISSAO , A.SIT_PROPOSTA , A.COD_USUARIO , A.CANAL_PROPOSTA , A.NSAS_SIVPF , A.ORIGEM_PROPOSTA , A.NSL , A.NSAC_SIVPF , A.SITUACAO_ENVIO , B.NUM_ENDOSSO FROM SEGUROS.PROPOSTA_FIDELIZ A , SEGUROS.RELATORIOS B WHERE A.NUM_PROPOSTA_SIVPF = B.NUM_CERTIFICADO AND B.SIT_REGISTRO = ' ' AND B.IDE_SISTEMA = ' ' AND B.COD_RELATORIO = ' ' ORDER BY A.COD_EMPRESA_SIVPF , A.NUM_PROPOSTA_SIVPF","sqlCode":999,"rowsCount":0,"Time":"0 ms","Error":">>> Erro: ERROR [58005] [IBM][DB2.NET] SQL0902 An unexpected exception has occurred in Process: 13156 Thread 22 AppDomain: Name:testhost There are no context policies. Function: DB2DataReader.Read() CallStack: at System.Environment.get_StackTrace() at IBM.Data.Db2.DB2ConnPool.HandleUnknownErrors(String strFncMsg, Exception exception, Boolean bThrow) at IBM.Data.Db2.DB2DataReader.Read() at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1201 at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) at Dapper.SqlMapper.Query(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 737 at IA_ConverterCommons.QueryBasis`1.Open(Object procParams) in E:\\PROJETOS\\FOURSYS\\SIAS\\SIAS-Batch\\IA_ConverterCommons\\Basis\\QueryBasis.cs:line 234 at Sias.PessoaFisica.DB2.PF0100B.PF0100B_PROPOSTA_FIDELIZ.Open() in E:\\PROJETOS\\FOURSYS\\SIAS\\SIAS-Batch\\Sias.PessoaFisica\\DB2\\PF0100B\\PF0100B_PROPOSTA_FIDELIZ.cs:line 72 at Code.PF0100B.R0050_00_SELECIONA_MOVTO_DB_OPEN_1() in E:\\PROJETOS\\FOURSYS\\SIAS\\SIAS-Batch\\Sias.PessoaFisica\\Code\\PF0100B.cs:line 715 at FileTests.Test_DB.PF0100B_Tests_DB.PF0100B_Database() in E:\\PROJETOS\\FOURSYS\\SIAS\\SIAS-Batch\\FileTests.Test\\FileTests.Test\\PF0100B_Tests_DB.cs:line 26 at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor) at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance) in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 151 at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 278 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<InvokeTestMethodAsync>b__1() at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<InvokeTestMethodAsync>b__0() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 243 at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance) in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 242 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance) at Xunit.Sdk.XunitTestInvoker.InvokeTestMethodAsync(Object testClassInstance) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestInvoker.cs:line 112 at Xunit.Sdk.TestInvoker`1.<RunAsync>b__47_0() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 207 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestInvoker`1.<RunAsync>b__47_0() at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 107 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) at Xunit.Sdk.TestInvoker`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 190 at Xunit.Sdk.XunitTestRunner.InvokeTestMethodAsync(ExceptionAggregator aggregator) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestRunner.cs:line 84 at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestRunner.cs:line 67 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator) at Xunit.Sdk.TestRunner`1.<>c__DisplayClass43_0.<RunAsync>b__0() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestRunner.cs:line 149 at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 107 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) at Xunit.Sdk.TestRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestRunner.cs:line 149 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestRunner`1.RunAsync() at Xunit.Sdk.XunitTestCaseRunner.RunTestAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestCaseRunner.cs:line 139 at Xunit.Sdk.TestCaseRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestCaseRunner.cs:line 82 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestCaseRunner`1.RunAsync() at Xunit.Sdk.XunitTestCase.RunAsync(IMessageSink diagnosticMessageSink, IMessageBus messageBus, Object[] constructorArguments, ExceptionAggregator aggregator, CancellationTokenSource cancellationTokenSource) in /_/src/xunit.execution/Sdk/Frameworks/XunitTestCase.cs:line 162 at Xunit.Sdk.XunitTestMethodRunner.RunTestCaseAsync(IXunitTestCase testCase) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestMethodRunner.cs:line 45 at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestMethodRunner.cs:line 136 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync() at Xunit.Sdk.TestMethodRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestMethodRunner.cs:line 106 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestMethodRunner`1.RunAsync() at Xunit.Sdk.XunitTestClassRunner.RunTestMethodAsync(ITestMethod testMethod, IReflectionMethodInfo method, IEnumerable`1 testCases, Object[] constructorArguments) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestClassRunner.cs:line 199 at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync() at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync() at Xunit.Sdk.TestClassRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestClassRunner.cs:line 175 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestClassRunner`1.RunAsync() at Xunit.Sdk.XunitTestCollectionRunner.RunTestClassAsync(ITestClass testClass, IReflectionTypeInfo class, IEnumerable`1 testCases) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestCollectionRunner.cs:line 185 at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync() at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync() at Xunit.Sdk.TestCollectionRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestCollectionRunner.cs:line 101 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestCollectionRunner`1.RunAsync() at Xunit.Sdk.XunitTestAssemblyRunner.RunTestCollectionAsync(IMessageBus messageBus, ITestCollection testCollection, IEnumerable`1 testCases, CancellationTokenSource cancellationTokenSource) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestAssemblyRunner.cs:line 262 at Xunit.Sdk.XunitTestAssemblyRunner.<>c__DisplayClass14_2.<RunTestCollectionsAsync>b__2() in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestAssemblyRunner.cs:line 211 at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) at System.Threading.Tasks.Task.ExecuteEntry() at System.Threading.Tasks.SynchronizationContextTaskScheduler.<>c.<.cctor>b__8_0(Object s) at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, Object state) in /_/src/xunit.execution/Sdk/MaxConcurrencySyncContext.cs:line 106 at Xunit.Sdk.MaxConcurrencySyncContext.<>c__DisplayClass11_0.<WorkerThreadProc>b__0(Object _) in /_/src/xunit.execution/Sdk/MaxConcurrencySyncContext.cs:line 96 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at Xunit.Sdk.ExecutionContextHelper.Run(Object context, Action`1 action) in /_/src/xunit.execution/Sdk/Utility/ExecutionContextHelper.cs:line 110 at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc() in /_/src/xunit.execution/Sdk/MaxConcurrencySyncContext.cs:line 96 at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__5_0(Object _) in /_/src/common/XunitWorkerThread.cs:line 37 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) InnerException Message: Year, Month, and Day parameters describe an un-representable DateTime. Check InnerException property for more detail. SQLSTATE=58005"}
{"DBCallId":"164441e1-07d6-4b5b-a8b4-c77d729644a7","TimeStamp":"2024-12-16T14:46:04.9368633-03:00","Query":" SELECT VALUE(MAX(NSAS_SIVPF) ,0) FROM SEGUROS.ARQUIVOS_SIVPF WHERE SIGLA_ARQUIVO = ' ' AND SISTEMA_ORIGEM = '0000' WITH UR","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"a4a67f36-9050-4f7c-80e9-4fb753834467","TimeStamp":"2024-12-16T14:46:07.8455711-03:00","Query":" INSERT INTO SEGUROS.HIST_PROP_FIDELIZ VALUES ('000000000000000', ' ', '000000000', '000000000', ' ', ' ', '000000000', '0000', '0000')","sqlCode":0,"rowsCount":0,"Time":"0 ms","Error":">>> Erro: ERROR [42802] [IBM][DB2] SQL0117N The number of values assigned is not the same as the number of specified or implied columns or variables."}
{"DBCallId":"4f79b06c-8bb1-4069-b9da-e677c0658432","TimeStamp":"2024-12-16T14:46:08.9966641-03:00","Query":" UPDATE SEGUROS.PROPOSTA_FIDELIZ SET NSAS_SIVPF = '000000000', NSL = '000000000', COD_USUARIO = 'PF0100B' WHERE NUM_PROPOSTA_SIVPF = '000000000000000'","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"e76f4340-ce48-434e-aa71-dd6ef53177c2","TimeStamp":"2024-12-16T14:46:11.3015526-03:00","Query":" UPDATE SEGUROS.RELATORIOS SET SIT_REGISTRO = '1' , TIMESTAMP = CURRENT TIMESTAMP WHERE NUM_CERTIFICADO = '000000000000000' AND SIT_REGISTRO = ' ' AND IDE_SISTEMA = ' ' AND COD_RELATORIO = ' '","sqlCode":0,"rowsCount":5,"Time":"0 ms","Error":""}
{"DBCallId":"b9b25743-556e-4aba-bd03-b63bc5cd3432","TimeStamp":"2024-12-16T14:46:12.1687628-03:00","Query":" INSERT INTO SEGUROS.ARQUIVOS_SIVPF VALUES ('BENEFAE ', '0000', '000000000', '2024-12-06', '000000000', '2024-12-06')","sqlCode":999,"rowsCount":0,"Time":"0 ms","Error":">>> Erro: ERROR [23505] [IBM][DB2] SQL0803N One or more values in the INSERT statement, UPDATE statement, or foreign key update caused by a DELETE statement are not valid because the primary key, unique constraint or unique index identified by \"IPPFT008\" constrains table \"000000A9D4\" from having duplicate values for the index key. SQLSTATE=23505"}