{"DBCallId":"f1ab4ee8-226d-4547-af9d-0458d35cd9ff","TimeStamp":"2024-12-16T14:42:33.9184165-03:00","Query":" SELECT DTMOVABE , DTMOVABE - 30 DAYS , DTMOVABE - 45 DAYS FROM SEGUROS.V1SISTEMA WHERE IDSISTEM = 'VA'","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"30d9dc7b-d0c0-47d0-a8c0-b779ac08edeb","TimeStamp":"2024-12-16T14:42:45.9086049-03:00","Query":"SELECT B.NUM_APOLICE , B.CODSUBES , B.NRCERTIF , B.DTQITBCO , B.DTQITBCO + 30 DAYS , B.SITUACAO , B.DPS_TITULAR , B.DPS_ESPOSA FROM SEGUROS.V0PRODUTOSVG A , SEGUROS.V0PROPOSTAVA B , SEGUROS.V0COBERPROPVA C WHERE B.NUM_APOLICE = A.NUM_APOLICE AND B.CODSUBES = A.CODSUBES AND B.SITUACAO IN ( '1' , '9' , 'E' ) AND C.OCORHIST = B.OCORHIST AND C.NRCERTIF = B.NRCERTIF","sqlCode":999,"rowsCount":0,"Time":"1 ms","Error":">>> Erro: ERROR [58005] [IBM][DB2.NET] SQL0902 An unexpected exception has occurred in Process: 13156 Thread 28 AppDomain: Name:testhost There are no context policies. Function: DB2DataReader.Read() CallStack: at System.Environment.get_StackTrace() at IBM.Data.Db2.DB2ConnPool.HandleUnknownErrors(String strFncMsg, Exception exception, Boolean bThrow) at IBM.Data.Db2.DB2DataReader.Read() at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1201 at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 815 at Dapper.SqlMapper.Query(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 737 at IA_ConverterCommons.QueryBasis`1.Open(Object procParams) in E:\\PROJETOS\\FOURSYS\\SIAS\\SIAS-Batch\\IA_ConverterCommons\\Basis\\QueryBasis.cs:line 234 at Sias.VidaAzul.DB2.VA0459B.VA0459B_TCOMIS.Open() in E:\\PROJETOS\\FOURSYS\\SIAS\\SIAS-Batch\\Sias.VidaAzul\\DB2\\VA0459B\\VA0459B_TCOMIS.cs:line 43 at Code.VA0459B.R0900_00_DECLARE_PROPOSTAS_VA_DB_OPEN_1() in E:\\PROJETOS\\FOURSYS\\SIAS\\SIAS-Batch\\Sias.VidaAzul\\Code\\VA0459B.cs:line 470 at FileTests.Test_DB.VA0459B_Tests_DB.VA0459B_Database() in E:\\PROJETOS\\FOURSYS\\SIAS\\SIAS-Batch\\FileTests.Test\\FileTests.Test\\VA0459B_Tests_DB.cs:line 25 at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor) at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance) in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 151 at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 278 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<InvokeTestMethodAsync>b__1() at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<InvokeTestMethodAsync>b__0() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 243 at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance) in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 242 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance) at Xunit.Sdk.XunitTestInvoker.InvokeTestMethodAsync(Object testClassInstance) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestInvoker.cs:line 112 at Xunit.Sdk.TestInvoker`1.<RunAsync>b__47_0() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 207 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestInvoker`1.<RunAsync>b__47_0() at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 107 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) at Xunit.Sdk.TestInvoker`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 190 at Xunit.Sdk.XunitTestRunner.InvokeTestMethodAsync(ExceptionAggregator aggregator) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestRunner.cs:line 84 at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestRunner.cs:line 67 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator) at Xunit.Sdk.TestRunner`1.<>c__DisplayClass43_0.<RunAsync>b__0() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestRunner.cs:line 149 at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 107 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) at Xunit.Sdk.TestRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestRunner.cs:line 149 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestRunner`1.RunAsync() at Xunit.Sdk.XunitTestCaseRunner.RunTestAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestCaseRunner.cs:line 139 at Xunit.Sdk.TestCaseRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestCaseRunner.cs:line 82 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestCaseRunner`1.RunAsync() at Xunit.Sdk.XunitTestCase.RunAsync(IMessageSink diagnosticMessageSink, IMessageBus messageBus, Object[] constructorArguments, ExceptionAggregator aggregator, CancellationTokenSource cancellationTokenSource) in /_/src/xunit.execution/Sdk/Frameworks/XunitTestCase.cs:line 162 at Xunit.Sdk.XunitTestMethodRunner.RunTestCaseAsync(IXunitTestCase testCase) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestMethodRunner.cs:line 45 at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestMethodRunner.cs:line 136 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync() at Xunit.Sdk.TestMethodRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestMethodRunner.cs:line 106 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestMethodRunner`1.RunAsync() at Xunit.Sdk.XunitTestClassRunner.RunTestMethodAsync(ITestMethod testMethod, IReflectionMethodInfo method, IEnumerable`1 testCases, Object[] constructorArguments) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestClassRunner.cs:line 199 at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync() at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync() at Xunit.Sdk.TestClassRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestClassRunner.cs:line 175 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestClassRunner`1.RunAsync() at Xunit.Sdk.XunitTestCollectionRunner.RunTestClassAsync(ITestClass testClass, IReflectionTypeInfo class, IEnumerable`1 testCases) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestCollectionRunner.cs:line 185 at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync() at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync() at Xunit.Sdk.TestCollectionRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestCollectionRunner.cs:line 101 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestCollectionRunner`1.RunAsync() at Xunit.Sdk.XunitTestAssemblyRunner.RunTestCollectionAsync(IMessageBus messageBus, ITestCollection testCollection, IEnumerable`1 testCases, CancellationTokenSource cancellationTokenSource) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestAssemblyRunner.cs:line 262 at Xunit.Sdk.XunitTestAssemblyRunner.<>c__DisplayClass14_2.<RunTestCollectionsAsync>b__2() in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestAssemblyRunner.cs:line 211 at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) at System.Threading.Tasks.Task.ExecuteEntry() at System.Threading.Tasks.SynchronizationContextTaskScheduler.<>c.<.cctor>b__8_0(Object s) at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, Object state) in /_/src/xunit.execution/Sdk/MaxConcurrencySyncContext.cs:line 106 at Xunit.Sdk.MaxConcurrencySyncContext.<>c__DisplayClass11_0.<WorkerThreadProc>b__0(Object _) in /_/src/xunit.execution/Sdk/MaxConcurrencySyncContext.cs:line 96 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at Xunit.Sdk.ExecutionContextHelper.Run(Object context, Action`1 action) in /_/src/xunit.execution/Sdk/Utility/ExecutionContextHelper.cs:line 110 at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc() in /_/src/xunit.execution/Sdk/MaxConcurrencySyncContext.cs:line 96 at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__5_0(Object _) in /_/src/common/XunitWorkerThread.cs:line 37 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) InnerException Message: rc = -2029059908 Check InnerException property for more detail. SQLSTATE=58005"}
{"DBCallId":"a925a30f-3d2f-42c4-86de-0f6702d9da13","TimeStamp":"2024-12-16T14:42:49.0391245-03:00","Query":" SELECT NUM_SICOB FROM SEGUROS.CONVERSAO_SICOB WHERE NUM_PROPOSTA_SIVPF = '000000000000000'","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"45b68368-b10f-42d9-b441-af443e732566","TimeStamp":"2024-12-16T14:42:50.4761353-03:00","Query":" SELECT SITUACAO FROM SEGUROS.V0RCAP WHERE NRTIT = '0000000000000' AND OPERACAO >= 100 AND OPERACAO <= 299 AND SITUACAO = '0'","sqlCode":0,"rowsCount":0,"Time":"0 ms","Error":""}
{"DBCallId":"3d7566f2-0953-498b-88ba-a1f2fcae6ea6","TimeStamp":"2024-12-16T14:43:28.4720521-03:00","Query":" SELECT COUNT(*) FROM SEGUROS.VG_ANDAMENTO_PROP WHERE NUM_CERTIFICADO = '000000000000000'","sqlCode":999,"rowsCount":0,"Time":"0 ms","Error":">>> Erro: ExecuteReader requires an open connection. The connection's current state is Closed."}
{"DBCallId":"6f1f146f-f032-43e8-b8b6-0375639c874a","TimeStamp":"2024-12-16T14:43:57.5434175-03:00","Query":" SELECT COUNT(*) FROM SEGUROS.V0ERROSPROPVA WHERE NRCERTIF = '000000000000000' AND COD_ERRO IN (1803 , 1804)","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"3a008e9f-0053-4c58-9014-50c9f5d31f99","TimeStamp":"2024-12-16T14:44:43.1760842-03:00","Query":" INSERT INTO SEGUROS.RELATORIOS VALUES ( 'VA0459B' , '2024-07-19', 'VA' , 'VA0469B' , 0, 0, '2024-07-19', '2024-07-19', '2024-07-19', 0, 0, 0, 0, 0, 0, 0, 0, '0000000000000', 0, 1, '000000000000000', 0, '0000', 9, 0, 0, ' ' , ' ' , 0, 0, ' ' , 0, 0, ' ' , '0' , ' ' , ' ' , NULL, 0, 0, CURRENT TIMESTAMP)","sqlCode":999,"rowsCount":0,"Time":"0 ms","Error":">>> Erro: ExecuteNonQuery requires an open connection. The connection's current state is Closed."}
{"DBCallId":"65ba0c3f-5890-4d13-a208-fbc77a586272","TimeStamp":"2024-12-16T14:44:44.3190242-03:00","Query":" INSERT INTO SEGUROS.ERROS_PROP_VIDAZUL VALUES ( '000000000000000', 1846 )","sqlCode":0,"rowsCount":0,"Time":"2 ms","Error":">>> Erro: ERROR [23505] [IBM][DB2] SQL0803N One or more values in the INSERT statement, UPDATE statement, or foreign key update caused by a DELETE statement are not valid because the primary key, unique constraint or unique index identified by \"I1VAT005\" constrains table \"00000082DA\" from having duplicate values for the index key. SQLSTATE=23505"}
{"DBCallId":"058c5b47-0ed4-4b66-8127-037b6f386e48","TimeStamp":"2024-12-16T14:44:45.9821199-03:00","Query":" UPDATE SEGUROS.PROPOSTAS_VA SET SIT_REGISTRO = '2' , DATA_MOVIMENTO = '2024-07-19', TIMESTAMP = CURRENT TIMESTAMP WHERE NUM_CERTIFICADO = '000000000000000'","sqlCode":999,"rowsCount":0,"Time":"0 ms","Error":""}